### PR TITLE
updates for new network generics

### PR DESCRIPTION
**Pull request by chad-klumb**

### CODE REVIEW

**Comment by chad-klumb** [comment]
apparently package cross-reference requirements are changing with r-devel, which is what 0e7decac60ede79b16b34eba4c2a7b8a6ba7d6dd addressed

**Comment by chad-klumb** [comment]
To my surprise `R CMD check` did not demand that I add `el` as an argument to `get.edge.attribute.active` despite it now appearing in the generic.  (Apparently before vs. after the dots makes a difference in this regard.)  Nonetheless, "Writing R Extensions" is pretty unequivocal,

> A method must have all the arguments of the generic, including … if the generic does.

so I've added it anyway.  If `el` is not missing in a call to `get.edge.attribute.active`, an error is now produced.

I also added a documentation entry for `get.edge.attribute.active`, which apparently didn't have one before.

**Comment by chad-klumb** [comment]
updated to depend on `master` branch of `network`

**Comment by skyebend** [comment]
@chad-klumb this is great!  I'm looking over PR, reviewing docs etc this week.  Do you know if reverse depends of networkDynamic have been tested with these changes?

**Comment by skyebend** [comment]
I checked out revdeps for tsna and ndtv, seem great!  I did find a broken link in the vignette (unrelated to these changes).  I think we should merge this PR and then I can do a couple of tweaks like that

**Comment by chad-klumb** [comment]
I have not run reverse dependencies of `networkDynamic`, but let me know if you need me to.

**Comment by chad-klumb** [comment]
Any objection to merging this now?  We are getting various packages ready for CRAN release and it's convenient if we can test all the updates together by using `master` versions of everything.

**Pull request merged**
